### ISSUE TITLE
Pokedex

### ISSUE THREAD

**Issue by anabneri** [WoMakersCode/challenges-back-end#1]
# Challenges Back End **POKEDEX**

-> Desafio POKEDÉX
Crie um sistema capaz de coletar dados do usuário que queira cadastrar um pokémon, este sistema deve ter as requisições Create, Update, Read e Delete, os dados devem estar salvos num banco de dados (NoSQL ou SQL) e ao final a aplicação deve estar numa nuvem.

_Requisitos adicionais: Usar um padrão de projeto, e ter testes unitários na aplicação._

**Comment by anabneri** [comment]
https://github.com/anabneri/Pokedex

**Comment by matteusmoreno** [comment]
https://github.com/matteusmoreno/SpringBoot/tree/main/pokedex
